//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.6421.
// 
#pragma warning disable 1591

namespace F02_InputWorkingTime.InputWorkingTimeWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InputWorkingTimeWSSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseDomainOfWorkingTimeRecode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseDomainOfReceiveingInformation))]
    public partial class InputWorkingTimeWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSharepointListKyuzuForInitialOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceiveingInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListWorkingTimeRecodeForFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSharepointItemWorkMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllSharePointWorkMasterListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateReceiveingInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback testUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateWorkingTimeRecodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrInsertWorkingTimeRecodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteWorkingTimeRecodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckRecieveExistInSPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InputWorkingTimeWS() {
            this.Url = global::F02_InputWorkingTime.Properties.Settings.Default.F02_InputWorkingTime_InputWorkingTimeWS_InputWorkingTimeWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event GetSharepointListKyuzuForInitialCompletedEventHandler GetSharepointListKyuzuForInitialCompleted;
        
        /// <remarks/>
        public event GetReceiveingInformationCompletedEventHandler GetReceiveingInformationCompleted;
        
        /// <remarks/>
        public event GetListWorkingTimeRecodeForFormCompletedEventHandler GetListWorkingTimeRecodeForFormCompleted;
        
        /// <remarks/>
        public event GetSharepointItemWorkMasterCompletedEventHandler GetSharepointItemWorkMasterCompleted;
        
        /// <remarks/>
        public event GetAllSharePointWorkMasterListCompletedEventHandler GetAllSharePointWorkMasterListCompleted;
        
        /// <remarks/>
        public event GetCurrentUserCompletedEventHandler GetCurrentUserCompleted;
        
        /// <remarks/>
        public event UpdateReceiveingInformationCompletedEventHandler UpdateReceiveingInformationCompleted;
        
        /// <remarks/>
        public event testUpdateCompletedEventHandler testUpdateCompleted;
        
        /// <remarks/>
        public event UpdateWorkingTimeRecodeCompletedEventHandler UpdateWorkingTimeRecodeCompleted;
        
        /// <remarks/>
        public event UpdateOrInsertWorkingTimeRecodeCompletedEventHandler UpdateOrInsertWorkingTimeRecodeCompleted;
        
        /// <remarks/>
        public event DeleteWorkingTimeRecodeCompletedEventHandler DeleteWorkingTimeRecodeCompleted;
        
        /// <remarks/>
        public event CheckRecieveExistInSPCompletedEventHandler CheckRecieveExistInSPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSharepointListKyuzuForInitial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SharePointKyuzuList[] GetSharepointListKyuzuForInitial() {
            object[] results = this.Invoke("GetSharepointListKyuzuForInitial", new object[0]);
            return ((SharePointKyuzuList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSharepointListKyuzuForInitialAsync() {
            this.GetSharepointListKyuzuForInitialAsync(null);
        }
        
        /// <remarks/>
        public void GetSharepointListKyuzuForInitialAsync(object userState) {
            if ((this.GetSharepointListKyuzuForInitialOperationCompleted == null)) {
                this.GetSharepointListKyuzuForInitialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSharepointListKyuzuForInitialOperationCompleted);
            }
            this.InvokeAsync("GetSharepointListKyuzuForInitial", new object[0], this.GetSharepointListKyuzuForInitialOperationCompleted, userState);
        }
        
        private void OnGetSharepointListKyuzuForInitialOperationCompleted(object arg) {
            if ((this.GetSharepointListKyuzuForInitialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSharepointListKyuzuForInitialCompleted(this, new GetSharepointListKyuzuForInitialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReceiveingInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceiveingInformation GetReceiveingInformation(string Key) {
            object[] results = this.Invoke("GetReceiveingInformation", new object[] {
                        Key});
            return ((ReceiveingInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetReceiveingInformationAsync(string Key) {
            this.GetReceiveingInformationAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetReceiveingInformationAsync(string Key, object userState) {
            if ((this.GetReceiveingInformationOperationCompleted == null)) {
                this.GetReceiveingInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceiveingInformationOperationCompleted);
            }
            this.InvokeAsync("GetReceiveingInformation", new object[] {
                        Key}, this.GetReceiveingInformationOperationCompleted, userState);
        }
        
        private void OnGetReceiveingInformationOperationCompleted(object arg) {
            if ((this.GetReceiveingInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceiveingInformationCompleted(this, new GetReceiveingInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListWorkingTimeRecodeForForm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorkingTimeRecode[] GetListWorkingTimeRecodeForForm(string Key) {
            object[] results = this.Invoke("GetListWorkingTimeRecodeForForm", new object[] {
                        Key});
            return ((WorkingTimeRecode[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListWorkingTimeRecodeForFormAsync(string Key) {
            this.GetListWorkingTimeRecodeForFormAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetListWorkingTimeRecodeForFormAsync(string Key, object userState) {
            if ((this.GetListWorkingTimeRecodeForFormOperationCompleted == null)) {
                this.GetListWorkingTimeRecodeForFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListWorkingTimeRecodeForFormOperationCompleted);
            }
            this.InvokeAsync("GetListWorkingTimeRecodeForForm", new object[] {
                        Key}, this.GetListWorkingTimeRecodeForFormOperationCompleted, userState);
        }
        
        private void OnGetListWorkingTimeRecodeForFormOperationCompleted(object arg) {
            if ((this.GetListWorkingTimeRecodeForFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListWorkingTimeRecodeForFormCompleted(this, new GetListWorkingTimeRecodeForFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSharepointItemWorkMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SharePointWorkMasterList GetSharepointItemWorkMaster(string Key) {
            object[] results = this.Invoke("GetSharepointItemWorkMaster", new object[] {
                        Key});
            return ((SharePointWorkMasterList)(results[0]));
        }
        
        /// <remarks/>
        public void GetSharepointItemWorkMasterAsync(string Key) {
            this.GetSharepointItemWorkMasterAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetSharepointItemWorkMasterAsync(string Key, object userState) {
            if ((this.GetSharepointItemWorkMasterOperationCompleted == null)) {
                this.GetSharepointItemWorkMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSharepointItemWorkMasterOperationCompleted);
            }
            this.InvokeAsync("GetSharepointItemWorkMaster", new object[] {
                        Key}, this.GetSharepointItemWorkMasterOperationCompleted, userState);
        }
        
        private void OnGetSharepointItemWorkMasterOperationCompleted(object arg) {
            if ((this.GetSharepointItemWorkMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSharepointItemWorkMasterCompleted(this, new GetSharepointItemWorkMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllSharePointWorkMasterList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SharePointWorkMasterList[] GetAllSharePointWorkMasterList() {
            object[] results = this.Invoke("GetAllSharePointWorkMasterList", new object[0]);
            return ((SharePointWorkMasterList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSharePointWorkMasterListAsync() {
            this.GetAllSharePointWorkMasterListAsync(null);
        }
        
        /// <remarks/>
        public void GetAllSharePointWorkMasterListAsync(object userState) {
            if ((this.GetAllSharePointWorkMasterListOperationCompleted == null)) {
                this.GetAllSharePointWorkMasterListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSharePointWorkMasterListOperationCompleted);
            }
            this.InvokeAsync("GetAllSharePointWorkMasterList", new object[0], this.GetAllSharePointWorkMasterListOperationCompleted, userState);
        }
        
        private void OnGetAllSharePointWorkMasterListOperationCompleted(object arg) {
            if ((this.GetAllSharePointWorkMasterListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSharePointWorkMasterListCompleted(this, new GetAllSharePointWorkMasterListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCurrentUser() {
            object[] results = this.Invoke("GetCurrentUser", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentUserAsync() {
            this.GetCurrentUserAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentUserAsync(object userState) {
            if ((this.GetCurrentUserOperationCompleted == null)) {
                this.GetCurrentUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentUserOperationCompleted);
            }
            this.InvokeAsync("GetCurrentUser", new object[0], this.GetCurrentUserOperationCompleted, userState);
        }
        
        private void OnGetCurrentUserOperationCompleted(object arg) {
            if ((this.GetCurrentUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentUserCompleted(this, new GetCurrentUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateReceiveingInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateReceiveingInformation(ReceiveingInformation Item) {
            this.Invoke("UpdateReceiveingInformation", new object[] {
                        Item});
        }
        
        /// <remarks/>
        public void UpdateReceiveingInformationAsync(ReceiveingInformation Item) {
            this.UpdateReceiveingInformationAsync(Item, null);
        }
        
        /// <remarks/>
        public void UpdateReceiveingInformationAsync(ReceiveingInformation Item, object userState) {
            if ((this.UpdateReceiveingInformationOperationCompleted == null)) {
                this.UpdateReceiveingInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateReceiveingInformationOperationCompleted);
            }
            this.InvokeAsync("UpdateReceiveingInformation", new object[] {
                        Item}, this.UpdateReceiveingInformationOperationCompleted, userState);
        }
        
        private void OnUpdateReceiveingInformationOperationCompleted(object arg) {
            if ((this.UpdateReceiveingInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateReceiveingInformationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/testUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void testUpdate() {
            this.Invoke("testUpdate", new object[0]);
        }
        
        /// <remarks/>
        public void testUpdateAsync() {
            this.testUpdateAsync(null);
        }
        
        /// <remarks/>
        public void testUpdateAsync(object userState) {
            if ((this.testUpdateOperationCompleted == null)) {
                this.testUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestUpdateOperationCompleted);
            }
            this.InvokeAsync("testUpdate", new object[0], this.testUpdateOperationCompleted, userState);
        }
        
        private void OntestUpdateOperationCompleted(object arg) {
            if ((this.testUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testUpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateWorkingTimeRecode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateWorkingTimeRecode(WorkingTimeRecode[] ListItem, WorkingTimeRecode[] ListItemBackUp) {
            this.Invoke("UpdateWorkingTimeRecode", new object[] {
                        ListItem,
                        ListItemBackUp});
        }
        
        /// <remarks/>
        public void UpdateWorkingTimeRecodeAsync(WorkingTimeRecode[] ListItem, WorkingTimeRecode[] ListItemBackUp) {
            this.UpdateWorkingTimeRecodeAsync(ListItem, ListItemBackUp, null);
        }
        
        /// <remarks/>
        public void UpdateWorkingTimeRecodeAsync(WorkingTimeRecode[] ListItem, WorkingTimeRecode[] ListItemBackUp, object userState) {
            if ((this.UpdateWorkingTimeRecodeOperationCompleted == null)) {
                this.UpdateWorkingTimeRecodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateWorkingTimeRecodeOperationCompleted);
            }
            this.InvokeAsync("UpdateWorkingTimeRecode", new object[] {
                        ListItem,
                        ListItemBackUp}, this.UpdateWorkingTimeRecodeOperationCompleted, userState);
        }
        
        private void OnUpdateWorkingTimeRecodeOperationCompleted(object arg) {
            if ((this.UpdateWorkingTimeRecodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateWorkingTimeRecodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrInsertWorkingTimeRecode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateOrInsertWorkingTimeRecode(WorkingTimeRecode Item) {
            this.Invoke("UpdateOrInsertWorkingTimeRecode", new object[] {
                        Item});
        }
        
        /// <remarks/>
        public void UpdateOrInsertWorkingTimeRecodeAsync(WorkingTimeRecode Item) {
            this.UpdateOrInsertWorkingTimeRecodeAsync(Item, null);
        }
        
        /// <remarks/>
        public void UpdateOrInsertWorkingTimeRecodeAsync(WorkingTimeRecode Item, object userState) {
            if ((this.UpdateOrInsertWorkingTimeRecodeOperationCompleted == null)) {
                this.UpdateOrInsertWorkingTimeRecodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrInsertWorkingTimeRecodeOperationCompleted);
            }
            this.InvokeAsync("UpdateOrInsertWorkingTimeRecode", new object[] {
                        Item}, this.UpdateOrInsertWorkingTimeRecodeOperationCompleted, userState);
        }
        
        private void OnUpdateOrInsertWorkingTimeRecodeOperationCompleted(object arg) {
            if ((this.UpdateOrInsertWorkingTimeRecodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrInsertWorkingTimeRecodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteWorkingTimeRecode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteWorkingTimeRecode(WorkingTimeRecode Item) {
            this.Invoke("DeleteWorkingTimeRecode", new object[] {
                        Item});
        }
        
        /// <remarks/>
        public void DeleteWorkingTimeRecodeAsync(WorkingTimeRecode Item) {
            this.DeleteWorkingTimeRecodeAsync(Item, null);
        }
        
        /// <remarks/>
        public void DeleteWorkingTimeRecodeAsync(WorkingTimeRecode Item, object userState) {
            if ((this.DeleteWorkingTimeRecodeOperationCompleted == null)) {
                this.DeleteWorkingTimeRecodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteWorkingTimeRecodeOperationCompleted);
            }
            this.InvokeAsync("DeleteWorkingTimeRecode", new object[] {
                        Item}, this.DeleteWorkingTimeRecodeOperationCompleted, userState);
        }
        
        private void OnDeleteWorkingTimeRecodeOperationCompleted(object arg) {
            if ((this.DeleteWorkingTimeRecodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteWorkingTimeRecodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckRecieveExistInSP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SharePointKyuzuList CheckRecieveExistInSP(ReceiveingInformation recieve) {
            object[] results = this.Invoke("CheckRecieveExistInSP", new object[] {
                        recieve});
            return ((SharePointKyuzuList)(results[0]));
        }
        
        /// <remarks/>
        public void CheckRecieveExistInSPAsync(ReceiveingInformation recieve) {
            this.CheckRecieveExistInSPAsync(recieve, null);
        }
        
        /// <remarks/>
        public void CheckRecieveExistInSPAsync(ReceiveingInformation recieve, object userState) {
            if ((this.CheckRecieveExistInSPOperationCompleted == null)) {
                this.CheckRecieveExistInSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckRecieveExistInSPOperationCompleted);
            }
            this.InvokeAsync("CheckRecieveExistInSP", new object[] {
                        recieve}, this.CheckRecieveExistInSPOperationCompleted, userState);
        }
        
        private void OnCheckRecieveExistInSPOperationCompleted(object arg) {
            if ((this.CheckRecieveExistInSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckRecieveExistInSPCompleted(this, new CheckRecieveExistInSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SharePointKyuzuList {
        
        private string receiveingNumberField;
        
        private string persionInChangeOfSalesField;
        
        private string typeOfCarField;
        
        private string symbolField;
        
        private string companyNameField;
        
        private string productNumberField;
        
        private string productNameField;
        
        private string typeOfModelField;
        
        private string personInChargeField;
        
        private string categotyField;
        
        private string deliveryDatePlanField;
        
        private string personInChargeOfHouanField;
        
        private string personInChargeOfCADField;
        
        private string manHourField;
        
        private System.Nullable<System.DateTime> deliveryDateActialField;
        
        private string remarkField;
        
        private string numberOfKataField;
        
        private string kyuzuField;
        
        private string cancelFlagField;
        
        private System.Guid idField;
        
        /// <remarks/>
        public string ReceiveingNumber {
            get {
                return this.receiveingNumberField;
            }
            set {
                this.receiveingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PersionInChangeOfSales {
            get {
                return this.persionInChangeOfSalesField;
            }
            set {
                this.persionInChangeOfSalesField = value;
            }
        }
        
        /// <remarks/>
        public string TypeOfCar {
            get {
                return this.typeOfCarField;
            }
            set {
                this.typeOfCarField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumber {
            get {
                return this.productNumberField;
            }
            set {
                this.productNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public string TypeOfModel {
            get {
                return this.typeOfModelField;
            }
            set {
                this.typeOfModelField = value;
            }
        }
        
        /// <remarks/>
        public string PersonInCharge {
            get {
                return this.personInChargeField;
            }
            set {
                this.personInChargeField = value;
            }
        }
        
        /// <remarks/>
        public string Categoty {
            get {
                return this.categotyField;
            }
            set {
                this.categotyField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryDatePlan {
            get {
                return this.deliveryDatePlanField;
            }
            set {
                this.deliveryDatePlanField = value;
            }
        }
        
        /// <remarks/>
        public string PersonInChargeOfHouan {
            get {
                return this.personInChargeOfHouanField;
            }
            set {
                this.personInChargeOfHouanField = value;
            }
        }
        
        /// <remarks/>
        public string PersonInChargeOfCAD {
            get {
                return this.personInChargeOfCADField;
            }
            set {
                this.personInChargeOfCADField = value;
            }
        }
        
        /// <remarks/>
        public string ManHour {
            get {
                return this.manHourField;
            }
            set {
                this.manHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeliveryDateActial {
            get {
                return this.deliveryDateActialField;
            }
            set {
                this.deliveryDateActialField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfKata {
            get {
                return this.numberOfKataField;
            }
            set {
                this.numberOfKataField = value;
            }
        }
        
        /// <remarks/>
        public string Kyuzu {
            get {
                return this.kyuzuField;
            }
            set {
                this.kyuzuField = value;
            }
        }
        
        /// <remarks/>
        public string CancelFlag {
            get {
                return this.cancelFlagField;
            }
            set {
                this.cancelFlagField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SharePointWorkMasterList {
        
        private string workerCodeField;
        
        private string workerNameField;
        
        private string[] administrationItemField;
        
        /// <remarks/>
        public string WorkerCode {
            get {
                return this.workerCodeField;
            }
            set {
                this.workerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string WorkerName {
            get {
                return this.workerNameField;
            }
            set {
                this.workerNameField = value;
            }
        }
        
        /// <remarks/>
        public string[] AdministrationItem {
            get {
                return this.administrationItemField;
            }
            set {
                this.administrationItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkingTimeRecode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseDomainOfWorkingTimeRecode {
        
        private string checkField;
        
        /// <remarks/>
        public string Check {
            get {
                return this.checkField;
            }
            set {
                this.checkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WorkingTimeRecode : BaseDomainOfWorkingTimeRecode {
        
        private string rECEIVEING_NUMField;
        
        private string wORK_ITEMField;
        
        private string wOKER_CDField;
        
        private string wOKER_NMField;
        
        private System.DateTime wORK_DATEField;
        
        private decimal wORKING_HOURSField;
        
        private System.DateTime uPD_DTField;
        
        /// <remarks/>
        public string RECEIVEING_NUM {
            get {
                return this.rECEIVEING_NUMField;
            }
            set {
                this.rECEIVEING_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string WORK_ITEM {
            get {
                return this.wORK_ITEMField;
            }
            set {
                this.wORK_ITEMField = value;
            }
        }
        
        /// <remarks/>
        public string WOKER_CD {
            get {
                return this.wOKER_CDField;
            }
            set {
                this.wOKER_CDField = value;
            }
        }
        
        /// <remarks/>
        public string WOKER_NM {
            get {
                return this.wOKER_NMField;
            }
            set {
                this.wOKER_NMField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime WORK_DATE {
            get {
                return this.wORK_DATEField;
            }
            set {
                this.wORK_DATEField = value;
            }
        }
        
        /// <remarks/>
        public decimal WORKING_HOURS {
            get {
                return this.wORKING_HOURSField;
            }
            set {
                this.wORKING_HOURSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UPD_DT {
            get {
                return this.uPD_DTField;
            }
            set {
                this.uPD_DTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiveingInformation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseDomainOfReceiveingInformation {
        
        private string checkField;
        
        /// <remarks/>
        public string Check {
            get {
                return this.checkField;
            }
            set {
                this.checkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveingInformation : BaseDomainOfReceiveingInformation {
        
        private string rECEIVEING_NUMField;
        
        private string dATA_NUMField;
        
        private string sIZE_WField;
        
        private string sIZE_DField;
        
        private string sIZE_HField;
        
        private string wEIGHTField;
        
        private System.Nullable<System.DateTime> cOMPLETED_DTField;
        
        private System.Nullable<System.DateTime> cAD_START_DTField;
        
        private System.Nullable<System.DateTime> mANUFACTURE_START_DTField;
        
        private System.Nullable<System.DateTime> hOUAN_CK_DTField;
        
        private System.Nullable<System.DateTime> kIBORI_CK_DTField;
        
        private System.Nullable<System.DateTime> cAD_CK_DTField;
        
        private System.Nullable<System.DateTime> cAM_CK_DTField;
        
        private System.Nullable<System.DateTime> sHIYOUZU_CK_DTField;
        
        private System.Nullable<System.DateTime> nC_CK_DTField;
        
        private System.Nullable<System.DateTime> wIRECUT_CK_DTField;
        
        private System.Nullable<System.DateTime> sHIAGE_CK_DTField;
        
        private System.Nullable<System.DateTime> kENSAHYOU_CK_DTField;
        
        private System.Nullable<System.DateTime> kENSA_CK_DTField;
        
        private System.Nullable<System.DateTime> cOMPLETED_CK_DTField;
        
        private string cANCEL_FLAGField;
        
        private string uPDATE_FLAGField;
        
        private string uPD_WOKER_CDField;
        
        private System.DateTime uPD_DTField;
        
        /// <remarks/>
        public string RECEIVEING_NUM {
            get {
                return this.rECEIVEING_NUMField;
            }
            set {
                this.rECEIVEING_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string DATA_NUM {
            get {
                return this.dATA_NUMField;
            }
            set {
                this.dATA_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string SIZE_W {
            get {
                return this.sIZE_WField;
            }
            set {
                this.sIZE_WField = value;
            }
        }
        
        /// <remarks/>
        public string SIZE_D {
            get {
                return this.sIZE_DField;
            }
            set {
                this.sIZE_DField = value;
            }
        }
        
        /// <remarks/>
        public string SIZE_H {
            get {
                return this.sIZE_HField;
            }
            set {
                this.sIZE_HField = value;
            }
        }
        
        /// <remarks/>
        public string WEIGHT {
            get {
                return this.wEIGHTField;
            }
            set {
                this.wEIGHTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> COMPLETED_DT {
            get {
                return this.cOMPLETED_DTField;
            }
            set {
                this.cOMPLETED_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CAD_START_DT {
            get {
                return this.cAD_START_DTField;
            }
            set {
                this.cAD_START_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> MANUFACTURE_START_DT {
            get {
                return this.mANUFACTURE_START_DTField;
            }
            set {
                this.mANUFACTURE_START_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> HOUAN_CK_DT {
            get {
                return this.hOUAN_CK_DTField;
            }
            set {
                this.hOUAN_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> KIBORI_CK_DT {
            get {
                return this.kIBORI_CK_DTField;
            }
            set {
                this.kIBORI_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CAD_CK_DT {
            get {
                return this.cAD_CK_DTField;
            }
            set {
                this.cAD_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CAM_CK_DT {
            get {
                return this.cAM_CK_DTField;
            }
            set {
                this.cAM_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SHIYOUZU_CK_DT {
            get {
                return this.sHIYOUZU_CK_DTField;
            }
            set {
                this.sHIYOUZU_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NC_CK_DT {
            get {
                return this.nC_CK_DTField;
            }
            set {
                this.nC_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> WIRECUT_CK_DT {
            get {
                return this.wIRECUT_CK_DTField;
            }
            set {
                this.wIRECUT_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SHIAGE_CK_DT {
            get {
                return this.sHIAGE_CK_DTField;
            }
            set {
                this.sHIAGE_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> KENSAHYOU_CK_DT {
            get {
                return this.kENSAHYOU_CK_DTField;
            }
            set {
                this.kENSAHYOU_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> KENSA_CK_DT {
            get {
                return this.kENSA_CK_DTField;
            }
            set {
                this.kENSA_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> COMPLETED_CK_DT {
            get {
                return this.cOMPLETED_CK_DTField;
            }
            set {
                this.cOMPLETED_CK_DTField = value;
            }
        }
        
        /// <remarks/>
        public string CANCEL_FLAG {
            get {
                return this.cANCEL_FLAGField;
            }
            set {
                this.cANCEL_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string UPDATE_FLAG {
            get {
                return this.uPDATE_FLAGField;
            }
            set {
                this.uPDATE_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string UPD_WOKER_CD {
            get {
                return this.uPD_WOKER_CDField;
            }
            set {
                this.uPD_WOKER_CDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UPD_DT {
            get {
                return this.uPD_DTField;
            }
            set {
                this.uPD_DTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetSharepointListKyuzuForInitialCompletedEventHandler(object sender, GetSharepointListKyuzuForInitialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSharepointListKyuzuForInitialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSharepointListKyuzuForInitialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SharePointKyuzuList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SharePointKyuzuList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetReceiveingInformationCompletedEventHandler(object sender, GetReceiveingInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceiveingInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceiveingInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceiveingInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceiveingInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetListWorkingTimeRecodeForFormCompletedEventHandler(object sender, GetListWorkingTimeRecodeForFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListWorkingTimeRecodeForFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListWorkingTimeRecodeForFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkingTimeRecode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkingTimeRecode[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetSharepointItemWorkMasterCompletedEventHandler(object sender, GetSharepointItemWorkMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSharepointItemWorkMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSharepointItemWorkMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SharePointWorkMasterList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SharePointWorkMasterList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetAllSharePointWorkMasterListCompletedEventHandler(object sender, GetAllSharePointWorkMasterListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSharePointWorkMasterListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSharePointWorkMasterListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SharePointWorkMasterList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SharePointWorkMasterList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void GetCurrentUserCompletedEventHandler(object sender, GetCurrentUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void UpdateReceiveingInformationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void testUpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void UpdateWorkingTimeRecodeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void UpdateOrInsertWorkingTimeRecodeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void DeleteWorkingTimeRecodeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    public delegate void CheckRecieveExistInSPCompletedEventHandler(object sender, CheckRecieveExistInSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckRecieveExistInSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckRecieveExistInSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SharePointKyuzuList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SharePointKyuzuList)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591